# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
- sudo gem install bundler
- gem unpack eventmachine -v '1.0.9.1'
- cd eventmachine-1.0.9.1
- wget https://github.com/eventmachine/eventmachine/raw/master/eventmachine.gemspec
- gem build eventmachine.gemspec
- sudo gem install eventmachine-1.0.9.1.gem
- bundle install
- sudo gem install jekyll

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
