title: Data Management in Life Sciences

plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/slate

markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

include: ['datatypes']
